# -*- coding: utf-8 -*-
"""ZaraIQ_Team1_Colab (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyyC0QsLA3XEgooUlkhzRnt3fuScxpOu

# ZaraIQ — Team 1: Demand Forecasting
Run cells top to bottom. Dataset is auto-downloaded from Kaggle via `kagglehub`.
If that fails, you will be prompted to upload `zaraSales.csv` manually.
"""

# CELL 1 — Install dependencies
!pip install -q xgboost shap kagglehub
print('Done.')

# CELL 2 — Load dataset
import os

DATA_PATH = None

try:
    import kagglehub
    kaggle_path = kagglehub.dataset_download('marixe/zara-sales-for-eda')
    print('Kaggle download path:', kaggle_path)
    for root, dirs, files_list in os.walk(kaggle_path):
        for f in files_list:
            if f.lower().endswith('.csv'):
                DATA_PATH = os.path.join(root, f)
                print('Found CSV:', DATA_PATH)
                break
        if DATA_PATH:
            break
except Exception as e:
    print('Kaggle download failed:', e)

if DATA_PATH is None:
    from google.colab import files as colab_files
    print('Please upload zaraSales.csv manually:')
    uploaded = colab_files.upload()
    DATA_PATH = list(uploaded.keys())[0]

os.makedirs('/content/outputs', exist_ok=True)
print('Using dataset:', DATA_PATH)
print('Output folder ready: /content/outputs')

# CELL 3 — Imports
import json, warnings
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import shap

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from xgboost import XGBRegressor

warnings.filterwarnings('ignore')
SEED = 42
print('All imports OK.')

# CELL 4 — Load and inspect raw data
df = pd.read_csv(DATA_PATH, sep=';')

print(f'Shape: {df.shape}')
print(f'\nColumns: {df.columns.tolist()}')

nulls = df.isnull().sum()
print(f'\nNull counts (non-zero columns only):')
print(nulls[nulls > 0])

print(f'\nSales Volume stats:')
print(df['Sales Volume'].describe())

print(f'\nUnique values per column:')
for col in df.columns:
    print(f'  {col:<25} {df[col].nunique():>5} unique')

df.head(3)

# CELL 5 — EDA plots
fig, axes = plt.subplots(2, 3, figsize=(16, 9))
fig.suptitle('ZaraIQ — Exploratory Data Analysis', fontsize=14, fontweight='bold')

axes[0,0].hist(df['Sales Volume'], bins=40, color='steelblue', edgecolor='white')
axes[0,0].set_title('Sales Volume (raw) — right-skewed')
axes[0,0].set_xlabel('Units Sold')

axes[0,1].hist(np.log1p(df['Sales Volume']), bins=40, color='teal', edgecolor='white')
axes[0,1].set_title('log1p(Sales Volume) — normalised')
axes[0,1].set_xlabel('log1p(Units Sold)')

promo = df.groupby('Promotion')['Sales Volume'].mean()
axes[0,2].bar(promo.index, promo.values, color=['#e63946', '#2a9d8f'])
axes[0,2].set_title('Mean Sales by Promotion status')
axes[0,2].set_ylabel('Mean Units Sold')
for i, v in enumerate(promo.values):
    axes[0,2].text(i, v + 10, f'{v:.0f}', ha='center', fontsize=9)

pos = df.groupby('Product Position')['Sales Volume'].mean().sort_values(ascending=False)
axes[1,0].bar(pos.index, pos.values, color='#457b9d')
axes[1,0].set_title('Mean Sales by Product Position')
axes[1,0].tick_params(axis='x', rotation=15)
for i, v in enumerate(pos.values):
    axes[1,0].text(i, v + 10, f'{v:.0f}', ha='center', fontsize=9)

seas = df.groupby('season')['Sales Volume'].mean().sort_values(ascending=False)
axes[1,1].bar(seas.index, seas.values, color='#e9c46a')
axes[1,1].set_title('Mean Sales by Season')
for i, v in enumerate(seas.values):
    axes[1,1].text(i, v + 10, f'{v:.0f}', ha='center', fontsize=9)

axes[1,2].scatter(df['price'], df['Sales Volume'], alpha=0.15, s=5, color='#264653')
axes[1,2].set_title('Price vs Sales Volume')
axes[1,2].set_xlabel('Price (USD)')
axes[1,2].set_ylabel('Units Sold')

plt.tight_layout()
plt.savefig('/content/outputs/eda_plots.png', dpi=120, bbox_inches='tight')
plt.show()
print('EDA plots saved.')

# CELL 6 — Clean: drop nulls and zero-variance columns
print(f'Rows before cleaning: {len(df)}')

df = df.dropna(subset=['name', 'description'])
print(f'After dropping null name/description: {len(df)}')

# Stash display columns BEFORE encoding
display_df = df[['Product ID', 'name', 'description', 'Sales Volume']].copy()

zero_var_cols = ['Product Category', 'brand', 'currency', 'url']
df = df.drop(columns=zero_var_cols, errors='ignore')
print(f'Dropped zero-variance columns: {zero_var_cols}')
print(f'Remaining columns: {df.columns.tolist()}')

# CELL 7 — Feature engineering

# Binary encode Yes/No and WOMAN/MAN
df['Promotion'] = df['Promotion'].map({'Yes': 1, 'No': 0}).fillna(0).astype(int)
df['Seasonal']  = df['Seasonal'].map({'Yes': 1, 'No': 0}).fillna(0).astype(int)
df['section']   = df['section'].map({'WOMAN': 1, 'MAN': 0}).fillna(0).astype(int)
print('Binary encoding done: Promotion, Seasonal, section')

# price_tier — before dropping price
df['price_tier'] = pd.cut(
    df['price'], bins=[0, 25, 50, 80, 999], labels=[0, 1, 2, 3]
).astype(int)
print('Engineered: price_tier')

# lead_time_tier — before dropping origin
lead_map = {
    'Turkey': 0, 'Morocco': 0, 'Spain': 0, 'Portugal': 0,
    'India': 1, 'Brazil': 1, 'Argentina': 1, 'Pakistan': 1,
    'China': 2, 'Bangladesh': 2, 'Vietnam': 2, 'Cambodia': 2,
}
df['lead_time_tier'] = df['origin'].map(lead_map).fillna(1).astype(int)
df = df.drop(columns=['origin'])
print('Engineered: lead_time_tier (raw origin dropped)')

# One-hot encode multi-class categoricals
cat_cols = ['Product Position', 'season', 'terms', 'material']
df = pd.get_dummies(df, columns=cat_cols, drop_first=False)
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)
print(f'One-hot encoded: {cat_cols}')

# in_season_flag — product is seasonal AND it's the matching season
season_match = {
    'terms_jackets':   'season_Autumn',
    'terms_sweaters':  'season_Winter',
    'terms_t-shirts':  'season_Summer',
    'terms_shoes':     'season_Spring',
    'terms_jeans':     'season_Autumn',
}
df['in_season_flag'] = 0
for term_col, season_col in season_match.items():
    if term_col in df.columns and season_col in df.columns:
        df['in_season_flag'] = (
            df['in_season_flag'] |
            ((df['Seasonal'] == 1) & (df[term_col] == 1) & (df[season_col] == 1)).astype(int)
        )
print('Engineered: in_season_flag')

# promo_x_position — promoted AND Front of Store
front_col = 'Product Position_Front of Store'
if front_col in df.columns:
    df['promo_x_position'] = ((df['Promotion'] == 1) & (df[front_col] == 1)).astype(int)
else:
    df['promo_x_position'] = 0
print('Engineered: promo_x_position')

print(f'\nTotal columns after feature engineering: {len(df.columns)}')
df.head(2)

# CELL 8 — Target transform + train/test split

y_raw = df['Sales Volume'].copy()
y_log = np.log1p(y_raw.values)

print(f'Skew BEFORE log1p : {y_raw.skew():.3f}')
print(f'Skew AFTER  log1p : {pd.Series(y_log).skew():.3f}')

# Build feature matrix — drop target and display columns
drop_for_model = ['Sales Volume', 'Product ID', 'name', 'description']
X_df = df.drop(columns=drop_for_model, errors='ignore')

feature_columns = X_df.columns.tolist()
X = X_df.values.astype(float)
y = y_log

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED
)

print(f'\nTotal features  : {len(feature_columns)}')
print(f'Train samples   : {X_train.shape[0]}')
print(f'Test  samples   : {X_test.shape[0]}')

# Save feature_columns.json — integration contract with ERP frontend
with open('/content/outputs/feature_columns.json', 'w') as f:
    json.dump(feature_columns, f, indent=2)
print('\nSaved: /content/outputs/feature_columns.json')

# CELL 9 — Train XGBoost (primary model)

xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=SEED,
    n_jobs=-1,
    verbosity=0,
)

print('Running 5-fold CV (XGBoost)...')
cv_xgb = cross_val_score(xgb_model, X_train, y_train, cv=5, scoring='r2', n_jobs=-1)
print(f'  CV R² per fold : {cv_xgb.round(4)}')
print(f'  CV R² mean     : {cv_xgb.mean():.4f} ± {cv_xgb.std():.4f}')

xgb_model.fit(X_train, y_train)

# Evaluate — inverse log1p so RMSE is in real units
y_pred_xgb_log = xgb_model.predict(X_test)
y_pred_xgb_raw = np.expm1(y_pred_xgb_log)
y_test_raw     = np.expm1(y_test)

xgb_rmse   = np.sqrt(mean_squared_error(y_test_raw, y_pred_xgb_raw))
xgb_mae    = mean_absolute_error(y_test_raw, y_pred_xgb_raw)
xgb_r2     = r2_score(y_test_raw, y_pred_xgb_raw)
xgb_r2_log = r2_score(y_test, y_pred_xgb_log)

print(f'\nXGBoost test metrics (original units):')
print(f'  RMSE     : {xgb_rmse:.2f} units')
print(f'  MAE      : {xgb_mae:.2f} units')
print(f'  R²       : {xgb_r2:.4f}')
print(f'  R² (log) : {xgb_r2_log:.4f}')

feat_imp = dict(zip(feature_columns, xgb_model.feature_importances_.tolist()))
top10    = sorted(feat_imp.items(), key=lambda x: x[1], reverse=True)[:10]
print('\nTop 10 feature importances:')
for name, imp in top10:
    print(f'  {name:<45} {imp:.4f}')

joblib.dump(xgb_model, '/content/outputs/demand_model.pkl')
print('\nSaved: /content/outputs/demand_model.pkl')

# CELL 10 — Train Random Forest (baseline comparison)

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    random_state=SEED,
    n_jobs=-1,
)

print('Running 5-fold CV (Random Forest)...')
cv_rf = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='r2', n_jobs=-1)
print(f'  CV R² per fold : {cv_rf.round(4)}')
print(f'  CV R² mean     : {cv_rf.mean():.4f} ± {cv_rf.std():.4f}')

rf_model.fit(X_train, y_train)

y_pred_rf_raw = np.expm1(rf_model.predict(X_test))

rf_rmse = np.sqrt(mean_squared_error(y_test_raw, y_pred_rf_raw))
rf_mae  = mean_absolute_error(y_test_raw, y_pred_rf_raw)
rf_r2   = r2_score(y_test_raw, y_pred_rf_raw)

print(f'\nRandom Forest test metrics (original units):')
print(f'  RMSE : {rf_rmse:.2f} units')
print(f'  MAE  : {rf_mae:.2f} units')
print(f'  R²   : {rf_r2:.4f}')

print(f'\nModel comparison:')
print(f'  XGBoost      R²: {xgb_r2:.4f}  RMSE: {xgb_rmse:.2f}')
print(f'  RandomForest R²: {rf_r2:.4f}  RMSE: {rf_rmse:.2f}')
winner = 'XGBoost' if xgb_r2 > rf_r2 else 'Random Forest'
print(f'  Winner: {winner}  (ΔR² = {abs(xgb_r2 - rf_r2):.4f})')

joblib.dump(rf_model, '/content/outputs/demand_rf.pkl')
print('\nSaved: /content/outputs/demand_rf.pkl')

# CELL 11 — Model comparison bar chart

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
fig.suptitle('XGBoost vs Random Forest — Test Set Comparison', fontsize=12, fontweight='bold')

models = ['XGBoost', 'Random Forest']
colors = ['#2a9d8f', '#e76f51']

bars1 = axes[0].bar(models, [xgb_r2, rf_r2], color=colors, width=0.4)
axes[0].set_title('R² Score (higher is better)')
axes[0].set_ylim(0, 1)
for bar, v in zip(bars1, [xgb_r2, rf_r2]):
    axes[0].text(bar.get_x() + bar.get_width()/2, v + 0.01, f'{v:.4f}', ha='center', fontsize=10, fontweight='bold')

bars2 = axes[1].bar(models, [xgb_rmse, rf_rmse], color=colors, width=0.4)
axes[1].set_title('RMSE (lower is better)')
axes[1].set_ylabel('RMSE (units)')
for bar, v in zip(bars2, [xgb_rmse, rf_rmse]):
    axes[1].text(bar.get_x() + bar.get_width()/2, v + 1, f'{v:.1f}', ha='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/outputs/model_comparison.png', dpi=120, bbox_inches='tight')
plt.show()
print('Model comparison chart saved.')

# CELL 12 — Save model_metrics.json

metrics = {
    'xgb_rmse'         : round(xgb_rmse, 4),
    'xgb_mae'          : round(xgb_mae,  4),
    'xgb_r2'           : round(xgb_r2,   4),
    'xgb_r2_log'       : round(xgb_r2_log, 4),
    'xgb_cv_r2_mean'   : round(float(cv_xgb.mean()), 4),
    'xgb_cv_r2_std'    : round(float(cv_xgb.std()),  4),
    'rf_rmse'          : round(rf_rmse, 4),
    'rf_mae'           : round(rf_mae,  4),
    'rf_r2'            : round(rf_r2,   4),
    'rf_cv_r2_mean'    : round(float(cv_rf.mean()), 4),
    'rf_cv_r2_std'     : round(float(cv_rf.std()),  4),
    'feature_importances': {k: round(v, 6) for k, v in feat_imp.items()},
    'n_train'          : int(X_train.shape[0]),
    'n_test'           : int(X_test.shape[0]),
    'n_features'       : len(feature_columns),
}

with open('/content/outputs/model_metrics.json', 'w') as f:
    json.dump(metrics, f, indent=2)

summary = {k: v for k, v in metrics.items() if k != 'feature_importances'}
print('Saved: /content/outputs/model_metrics.json')
print(json.dumps(summary, indent=2))

# CELL 13 — SHAP explainer + plots

print('Initialising SHAP TreeExplainer...')
explainer = shap.TreeExplainer(xgb_model)

# Beeswarm summary (100 samples — fast)
print('Computing SHAP values on 100 test samples...')
shap_vals_100 = explainer.shap_values(X_test[:100])

plt.figure(figsize=(10, 7))
shap.summary_plot(
    shap_vals_100, X_test[:100],
    feature_names=feature_columns,
    show=False, max_display=15
)
plt.title('SHAP Feature Impact — XGBoost', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/outputs/shap_summary_beeswarm.png', dpi=120, bbox_inches='tight')
plt.show()
print('SHAP beeswarm saved.')

# Waterfall for 3 individual test samples
print('\nGenerating SHAP waterfall for 3 sample products...')
shap_exp = explainer(X_test[:3])

fig, axes = plt.subplots(1, 3, figsize=(20, 6))
for i in range(3):
    plt.sca(axes[i])
    shap.plots.waterfall(shap_exp[i], max_display=10, show=False)
    pred_u   = int(round(np.expm1(y_pred_xgb_log[i])))
    actual_u = int(round(y_test_raw[i]))
    axes[i].set_title(f'Sample {i+1}\nPred: {pred_u} units | Actual: {actual_u} units', fontsize=10)

plt.tight_layout()
plt.savefig('/content/outputs/shap_waterfall_samples.png', dpi=120, bbox_inches='tight')
plt.show()
print('SHAP waterfall saved.')

joblib.dump(explainer, '/content/outputs/shap_explainer.pkl')
print('Saved: /content/outputs/shap_explainer.pkl')

# CELL 14 — Save zara_processed.csv

processed_df = X_df.copy()
processed_df.insert(0, 'Sales Volume', y_raw.values)
processed_df.insert(0, 'name',         display_df['name'].values)
processed_df.insert(0, 'Product ID',   display_df['Product ID'].values)

processed_df.to_csv('/content/outputs/zara_processed.csv', index=False)
print(f'Saved: /content/outputs/zara_processed.csv')
print(f'Shape: {processed_df.shape}')
processed_df.head(3)

# CELL 15 — predict_demand() helper + smoke test
# This exact function goes into utils/predict.py for the Streamlit ERP frontend.

def predict_demand(
    price,
    promotion,           # 'Yes' | 'No'
    product_position,    # 'Aisle' | 'End-cap' | 'Front of Store'
    seasonal,            # 'Yes' | 'No'
    season,              # 'Spring' | 'Summer' | 'Autumn' | 'Winter'
    terms,               # 'jackets' | 'sweaters' | 't-shirts' | 'shoes' | 'jeans'
    section,             # 'WOMAN' | 'MAN'
    material,            # e.g. 'Cotton', 'Linen Blend', 'Wool', ...
    origin,              # e.g. 'Turkey', 'China', ...
):
    """
    Returns:
        forecast      (int)   predicted units sold (original scale)
        shap_top5     (list)  top 5 [(feature, shap_value), ...]
        reorder_alert (bool)  True if high demand AND long lead time
        risk_level    (str)   'High' | 'Medium' | 'Low'
    """
    feat = {col: 0 for col in feature_columns}

    feat['price']     = float(price)
    feat['Promotion'] = 1 if promotion == 'Yes'   else 0
    feat['Seasonal']  = 1 if seasonal  == 'Yes'   else 0
    feat['section']   = 1 if section   == 'WOMAN' else 0

    for col in [
        f'Product Position_{product_position}',
        f'season_{season}',
        f'terms_{terms.lower()}',
        f'material_{material}',
    ]:
        if col in feat:
            feat[col] = 1

    feat['price_tier'] = int(
        pd.cut([price], bins=[0, 25, 50, 80, 999], labels=[0, 1, 2, 3])[0]
    )

    natural = {
        'jackets': 'Autumn', 'sweaters': 'Winter', 't-shirts': 'Summer',
        'shoes': 'Spring',   'jeans': 'Autumn',
    }
    feat['in_season_flag']   = int(seasonal == 'Yes' and season == natural.get(terms.lower(), ''))
    feat['promo_x_position'] = int(promotion == 'Yes' and product_position == 'Front of Store')

    lt_map = {
        'Turkey': 0, 'Morocco': 0, 'Spain': 0, 'Portugal': 0,
        'India': 1, 'Brazil': 1, 'Argentina': 1, 'Pakistan': 1,
        'China': 2, 'Bangladesh': 2, 'Vietnam': 2, 'Cambodia': 2,
    }
    feat['lead_time_tier'] = lt_map.get(origin, 1)

    x = np.array([feat[c] for c in feature_columns], dtype=float).reshape(1, -1)

    pred_log = float(xgb_model.predict(x)[0])
    forecast = int(round(np.expm1(pred_log)))

    shap_exp  = explainer(x)
    shap_dict = dict(zip(feature_columns, shap_exp.values[0].tolist()))
    shap_top5 = sorted(shap_dict.items(), key=lambda kv: abs(kv[1]), reverse=True)[:5]

    lt            = feat['lead_time_tier']
    reorder_alert = bool(forecast > 1200 and lt >= 2)
    if   forecast > 1500 and lt == 2: risk_level = 'High'
    elif forecast > 1200 and lt >= 1: risk_level = 'Medium'
    else:                              risk_level = 'Low'

    return forecast, shap_top5, reorder_alert, risk_level


# Smoke test 1
print('=== Test 1: Promo sweater, WOMAN, China (expect High risk) ===')
fc, shap5, alert, risk = predict_demand(
    price=45, promotion='Yes', product_position='Front of Store',
    seasonal='Yes', season='Winter', terms='sweaters',
    section='WOMAN', material='Cotton', origin='China'
)
print(f'  Forecast      : {fc} units')
print(f'  Risk level    : {risk}')
print(f'  Reorder alert : {alert}')
print('  Top 5 SHAP drivers:')
for name, val in shap5:
    print(f'    {"▲" if val > 0 else "▼"}  {name:<42} {abs(val):.4f}')

print()

# Smoke test 2
print('=== Test 2: No-promo jeans, MAN, Spain (expect Low risk) ===')
fc2, _, alert2, risk2 = predict_demand(
    price=20, promotion='No', product_position='Aisle',
    seasonal='No', season='Spring', terms='jeans',
    section='MAN', material='Denim', origin='Spain'
)
print(f'  Forecast      : {fc2} units')
print(f'  Risk level    : {risk2}')
print(f'  Reorder alert : {alert2}')

# CELL 16 — Final output checklist

required = [
    '/content/outputs/demand_model.pkl',
    '/content/outputs/demand_rf.pkl',
    '/content/outputs/shap_explainer.pkl',
    '/content/outputs/feature_columns.json',
    '/content/outputs/model_metrics.json',
    '/content/outputs/zara_processed.csv',
    '/content/outputs/shap_summary_beeswarm.png',
    '/content/outputs/shap_waterfall_samples.png',
    '/content/outputs/model_comparison.png',
    '/content/outputs/eda_plots.png',
]

print('=' * 52)
print('TEAM 1 OUTPUT CHECKLIST')
print('=' * 52)
all_ok = True
for path in required:
    exists = os.path.exists(path)
    size   = os.path.getsize(path) / 1024 if exists else 0
    status = '✅' if exists else '❌ MISSING'
    print(f'  {status}  {os.path.basename(path):<40} {size:>7.1f} KB')
    if not exists:
        all_ok = False

print()
if all_ok:
    print('All outputs present. Ready for ERP integration.')
else:
    print('Some files missing — rerun the relevant cells.')

# CELL 17 — Download all outputs as ZIP
import shutil
from google.colab import files as colab_files

zip_path = '/content/ZaraIQ_Team1_Outputs'
shutil.make_archive(zip_path, 'zip', '/content/outputs')
print('Zipped.')
colab_files.download(zip_path + '.zip')
print('Download started — check your browser for ZaraIQ_Team1_Outputs.zip')

# ═══════════════════════════════════════════════════════════════════════════════
# TEAM 1 — FULL MODEL EVALUATION
# Paste this as a NEW CELL in your Colab notebook and run it.
# Requires Cells 1–15 to have been run first.
# ═══════════════════════════════════════════════════════════════════════════════

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — TRAIN & TEST METRICS FOR BOTH MODELS
# ─────────────────────────────────────────────────────────────────────────────
print('=' * 60)
print('SECTION 1 — TRAIN & TEST METRICS')
print('=' * 60)

def get_metrics(model, X, y_log):
    pred_log = model.predict(X)
    pred_raw = np.expm1(pred_log)
    true_raw = np.expm1(y_log)
    return {
        'RMSE' : round(np.sqrt(mean_squared_error(true_raw, pred_raw)), 4),
        'MAE'  : round(mean_absolute_error(true_raw, pred_raw), 4),
        'R²'   : round(r2_score(true_raw, pred_raw), 4),
        'MAPE' : round(np.mean(np.abs((true_raw - pred_raw) / true_raw)) * 100, 4),
    }

xgb_train_m = get_metrics(xgb_model, X_train, y_train)
xgb_test_m  = get_metrics(xgb_model, X_test,  y_test)
rf_train_m  = get_metrics(rf_model,  X_train, y_train)
rf_test_m   = get_metrics(rf_model,  X_test,  y_test)

header = f"  {'Metric':<8}  {'XGB Train':>10}  {'XGB Test':>10}  {'RF Train':>10}  {'RF Test':>10}  {'XGB Gap':>10}  {'RF Gap':>10}"
print(header)
print('  ' + '-' * (len(header) - 2))
for metric in ['RMSE', 'MAE', 'R²', 'MAPE']:
    xgb_gap = round(xgb_train_m[metric] - xgb_test_m[metric], 4)
    rf_gap  = round(rf_train_m[metric]  - rf_test_m[metric],  4)
    print(f"  {metric:<8}  {xgb_train_m[metric]:>10}  {xgb_test_m[metric]:>10}  "
          f"{rf_train_m[metric]:>10}  {rf_test_m[metric]:>10}  "
          f"{xgb_gap:>+10}  {rf_gap:>+10}")

print()
print('  Interpretation:')
print(f'  XGBoost  — train R²: {xgb_train_m["R²"]}  test R²: {xgb_test_m["R²"]}  gap: {xgb_train_m["R²"]-xgb_test_m["R²"]:+.4f}')
print(f'  RF       — train R²: {rf_train_m["R²"]}  test R²: {rf_test_m["R²"]}  gap: {rf_train_m["R²"]-rf_test_m["R²"]:+.4f}')
gap_xgb = xgb_train_m['R²'] - xgb_test_m['R²']
if gap_xgb < 0.05:
    print('  ✅ XGBoost: gap < 0.05 — no significant overfitting.')
elif gap_xgb < 0.10:
    print('  🟡 XGBoost: mild overfitting (gap 0.05–0.10).')
else:
    print('  🔴 XGBoost: significant overfitting (gap > 0.10).')

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — TRAIN vs TEST BAR CHART (same style as your B3 image)
# ─────────────────────────────────────────────────────────────────────────────
print('\n' + '=' * 60)
print('SECTION 2 — TRAIN vs TEST METRICS CHART')
print('=' * 60)

metrics_to_plot = ['R²', 'RMSE', 'MAE', 'MAPE']
x = np.arange(len(metrics_to_plot))
width = 0.18

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Train vs Test Metrics — Overfitting Check\nIf Train >> Test → overfitting.  If both low → underfitting.',
             fontsize=13, fontweight='bold')

for ax, model_name, train_m, test_m, color_train, color_test in [
    (axes[0], 'XGBoost',       xgb_train_m, xgb_test_m, '#2d6a9f', '#1e8449'),
    (axes[1], 'Random Forest', rf_train_m,  rf_test_m,  '#2d6a9f', '#1e8449'),
]:
    train_vals = [train_m[m] for m in metrics_to_plot]
    test_vals  = [test_m[m]  for m in metrics_to_plot]
    gaps       = [round(t - v, 4) for t, v in zip(train_vals, test_vals)]

    bars_train = ax.bar(x - width/2, train_vals, width, label='Train', color=color_train)
    bars_test  = ax.bar(x + width/2, test_vals,  width, label='Test',  color=color_test)

    # Value labels on bars
    for bar, val in zip(bars_train, train_vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{val:.4f}', ha='center', va='bottom', fontsize=8, fontweight='bold', color='#2d6a9f')
    for bar, val, gap in zip(bars_test, test_vals, gaps):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{val:.4f}', ha='center', va='bottom', fontsize=8, fontweight='bold', color='#1e8449')
        gap_color = '#e74c3c' if abs(gap) > 0.05 else '#888888'
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.025,
                f'gap: {gap:+.4f}', ha='center', va='bottom', fontsize=7, color=gap_color)

    ax.set_title(f'{model_name}', fontsize=12, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(metrics_to_plot, fontsize=10)
    ax.set_ylabel('Score / Value')
    ax.legend()
    ax.set_ylim(0, max(max(train_vals), max(test_vals)) * 1.18)
    ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('/content/outputs/train_vs_test_metrics.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: /content/outputs/train_vs_test_metrics.png')

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — CORRELATION MATRIX
# ─────────────────────────────────────────────────────────────────────────────
print('\n' + '=' * 60)
print('SECTION 3 — CORRELATION MATRIX')
print('=' * 60)

# Use the processed feature dataframe + Sales Volume
corr_df = X_df.copy()
corr_df.insert(0, 'Sales Volume', y_raw.values)

# Keep only numeric columns and limit to meaningful ones (top correlated with target)
corr_matrix_full = corr_df.corr()
top_corr_cols = corr_matrix_full['Sales Volume'].abs().sort_values(ascending=False).head(16).index.tolist()
corr_subset = corr_df[top_corr_cols].corr()

print(f'Showing top 15 features most correlated with Sales Volume:')
target_corr = corr_matrix_full['Sales Volume'].drop('Sales Volume').sort_values(ascending=False)
print('\n  Positive correlations (increase Sales Volume):')
for col, val in target_corr[target_corr > 0].head(8).items():
    print(f'    {col:<45} {val:+.4f}')
print('\n  Negative correlations (decrease Sales Volume):')
for col, val in target_corr[target_corr < 0].tail(5).items():
    print(f'    {col:<45} {val:+.4f}')

fig, ax = plt.subplots(figsize=(14, 11))
mask = np.triu(np.ones_like(corr_subset, dtype=bool))
sns.heatmap(
    corr_subset,
    mask=mask,
    annot=True, fmt='.2f',
    cmap='RdYlGn',
    center=0, vmin=-1, vmax=1,
    linewidths=0.5,
    ax=ax,
    annot_kws={'size': 8},
)
ax.set_title('Correlation Matrix — Top 15 Features + Sales Volume', fontsize=13, fontweight='bold', pad=15)
plt.xticks(rotation=45, ha='right', fontsize=9)
plt.yticks(rotation=0, fontsize=9)
plt.tight_layout()
plt.savefig('/content/outputs/correlation_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: /content/outputs/correlation_matrix.png')

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — 20 RANDOM SYNTHETIC INPUTS (out-of-distribution validation)
# ─────────────────────────────────────────────────────────────────────────────
print('\n' + '=' * 60)
print('SECTION 4 — 20 RANDOM SYNTHETIC INPUTS (out-of-distribution)')
print('=' * 60)

import random
random.seed(99)

positions  = ['Front of Store', 'End-cap', 'Aisle']
seasons_l  = ['Spring', 'Summer', 'Autumn', 'Winter']
terms_l    = ['jackets', 'sweaters', 't-shirts', 'shoes', 'jeans']
sections_l = ['WOMAN', 'MAN']
materials  = ['Cotton', 'Linen Blend', 'Wool', 'Polyester', 'Denim',
               'Silk', 'Cashmere', 'Viscose', 'Nylon', 'Leather', 'Suede']
origins_l  = ['Turkey', 'Morocco', 'Spain', 'Portugal',
               'India', 'Brazil', 'Argentina', 'Pakistan',
               'China', 'Bangladesh', 'Vietnam', 'Cambodia']
lt_map = {
    'Turkey':0,'Morocco':0,'Spain':0,'Portugal':0,
    'India':1,'Brazil':1,'Argentina':1,'Pakistan':1,
    'China':2,'Bangladesh':2,'Vietnam':2,'Cambodia':2,
}
natural_season = {
    'jackets':'Autumn','sweaters':'Winter','t-shirts':'Summer',
    'shoes':'Spring','jeans':'Autumn',
}

def build_vector(price, promotion, product_position, seasonal, season,
                 terms, section, material, origin):
    feat = {col: 0 for col in feature_columns}
    feat['price']     = float(price)
    feat['Promotion'] = 1 if promotion == 'Yes' else 0
    feat['Seasonal']  = 1 if seasonal  == 'Yes' else 0
    feat['section']   = 1 if section   == 'WOMAN' else 0
    for col in [f'Product Position_{product_position}', f'season_{season}',
                f'terms_{terms.lower()}', f'material_{material}']:
        if col in feat: feat[col] = 1
    feat['price_tier'] = int(pd.cut([price], bins=[0,25,50,80,999], labels=[0,1,2,3])[0])
    feat['in_season_flag']   = int(seasonal == 'Yes' and season == natural_season.get(terms.lower(),''))
    feat['promo_x_position'] = int(promotion == 'Yes' and product_position == 'Front of Store')
    feat['lead_time_tier']   = lt_map.get(origin, 1)
    return np.array([feat[c] for c in feature_columns], dtype=float).reshape(1, -1)

# Generate 20 random configs
random_inputs = []
for i in range(20):
    price    = round(random.uniform(12, 135), 2)
    promo    = random.choice(['Yes', 'No'])
    pos      = random.choice(positions)
    seas_yn  = random.choice(['Yes', 'No'])
    season   = random.choice(seasons_l)
    term     = random.choice(terms_l)
    section  = random.choice(sections_l)
    material = random.choice(materials)
    origin   = random.choice(origins_l)
    random_inputs.append((price, promo, pos, seas_yn, season, term, section, material, origin))

# Predict with both models
results = []
for i, (price, promo, pos, seas_yn, season, term, section, material, origin) in enumerate(random_inputs, 1):
    x = build_vector(price, promo, pos, seas_yn, season, term, section, material, origin)

    xgb_pred = int(round(np.expm1(xgb_model.predict(x)[0])))
    rf_pred  = int(round(np.expm1(rf_model.predict(x)[0])))
    diff     = xgb_pred - rf_pred
    lt       = lt_map.get(origin, 1)
    risk     = 'High' if (xgb_pred > 1500 and lt == 2) else ('Medium' if (xgb_pred > 1200 and lt >= 1) else 'Low')

    results.append({
        'No.'       : i,
        'Price'     : price,
        'Promo'     : promo,
        'Position'  : pos,
        'Season'    : season,
        'Terms'     : term,
        'Section'   : section,
        'Material'  : material,
        'Origin'    : origin,
        'XGB Pred'  : xgb_pred,
        'RF Pred'   : rf_pred,
        'Difference': diff,
        'Risk'      : risk,
    })

results_df = pd.DataFrame(results)

print(f'\n{"No.":<4} {"Price":>7} {"Promo":>6} {"Position":<17} {"Season":<8} {"Terms":<11} {"Section":<7} {"Material":<13} {"Origin":<12} {"XGB":>6} {"RF":>6} {"Diff":>6} {"Risk"}')
print('-' * 130)
for _, row in results_df.iterrows():
    print(f'{int(row["No."]):>3}.  '
          f'{row["Price"]:>7.2f}  '
          f'{row["Promo"]:>5}  '
          f'{row["Position"]:<17} '
          f'{row["Season"]:<8} '
          f'{row["Terms"]:<11} '
          f'{row["Section"]:<7} '
          f'{row["Material"]:<13} '
          f'{row["Origin"]:<12} '
          f'{row["XGB Pred"]:>6}  '
          f'{row["RF Pred"]:>6}  '
          f'{row["Difference"]:>+6}  '
          f'{row["Risk"]}')

print(f'\nSummary statistics across 20 random inputs:')
print(f'  XGBoost — mean: {results_df["XGB Pred"].mean():.0f}  min: {results_df["XGB Pred"].min()}  max: {results_df["XGB Pred"].max()}  std: {results_df["XGB Pred"].std():.1f}')
print(f'  RF      — mean: {results_df["RF Pred"].mean():.0f}  min: {results_df["RF Pred"].min()}  max: {results_df["RF Pred"].max()}  std: {results_df["RF Pred"].std():.1f}')
print(f'  Mean absolute diff (XGB vs RF): {results_df["Difference"].abs().mean():.1f} units')
print(f'  Risk breakdown — High: {(results_df["Risk"]=="High").sum()}  Medium: {(results_df["Risk"]=="Medium").sum()}  Low: {(results_df["Risk"]=="Low").sum()}')

# Save to CSV
results_df.to_csv('/content/outputs/random_validation_20.csv', index=False)
print('\nSaved: /content/outputs/random_validation_20.csv')

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 5 — RANDOM INPUTS VISUALISATION
# ─────────────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.suptitle('20 Random Synthetic Inputs — XGBoost vs Random Forest Predictions',
             fontsize=13, fontweight='bold')

x_idx = np.arange(1, 21)

# Plot 1: Predictions side by side
axes[0].bar(x_idx - 0.3, results_df['XGB Pred'], 0.55, label='XGBoost', color='#2d6a9f', alpha=0.85)
axes[0].bar(x_idx + 0.3, results_df['RF Pred'],  0.55, label='RF',      color='#1e8449', alpha=0.85)
axes[0].axhline(y=results_df['XGB Pred'].mean(), color='#2d6a9f', linestyle='--', alpha=0.5, label=f'XGB mean ({results_df["XGB Pred"].mean():.0f})')
axes[0].axhline(y=results_df['RF Pred'].mean(),  color='#1e8449', linestyle='--', alpha=0.5, label=f'RF mean ({results_df["RF Pred"].mean():.0f})')
axes[0].set_title('Predicted Units (XGBoost vs RF)')
axes[0].set_xlabel('Input #')
axes[0].set_ylabel('Units Sold (predicted)')
axes[0].legend(fontsize=8)
axes[0].set_xticks(x_idx)
axes[0].grid(axis='y', alpha=0.3)

# Plot 2: Difference (XGB - RF)
diff_colors = ['#e74c3c' if d > 0 else '#2ecc71' for d in results_df['Difference']]
axes[1].bar(x_idx, results_df['Difference'], color=diff_colors, alpha=0.85)
axes[1].axhline(0, color='black', linewidth=0.8)
axes[1].set_title('Prediction Difference (XGB − RF)')
axes[1].set_xlabel('Input #')
axes[1].set_ylabel('Difference (units)')
axes[1].set_xticks(x_idx)
axes[1].grid(axis='y', alpha=0.3)

# Plot 3: Scatter XGB vs RF
sc = axes[2].scatter(results_df['XGB Pred'], results_df['RF Pred'],
                     c=results_df['Difference'].abs(), cmap='RdYlGn_r', s=80, alpha=0.85, zorder=3)
min_val = min(results_df['XGB Pred'].min(), results_df['RF Pred'].min()) - 20
max_val = max(results_df['XGB Pred'].max(), results_df['RF Pred'].max()) + 20
axes[2].plot([min_val, max_val], [min_val, max_val], 'k--', alpha=0.4, label='Perfect agreement')
for _, row in results_df.iterrows():
    axes[2].annotate(str(int(row['No.'])),
                     (row['XGB Pred'], row['RF Pred']),
                     textcoords='offset points', xytext=(4,4), fontsize=7)
plt.colorbar(sc, ax=axes[2], label='|XGB - RF|')
axes[2].set_title('XGB vs RF Agreement')
axes[2].set_xlabel('XGBoost Prediction')
axes[2].set_ylabel('Random Forest Prediction')
axes[2].legend(fontsize=8)
axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('/content/outputs/random_validation_chart.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: /content/outputs/random_validation_chart.png')

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 6 — ACTUAL vs PREDICTED SCATTER (Train AND Test)
# ─────────────────────────────────────────────────────────────────────────────
print('\n' + '=' * 60)
print('SECTION 6 — ACTUAL vs PREDICTED (Train & Test)')
print('=' * 60)

fig, axes = plt.subplots(2, 2, figsize=(14, 12))
fig.suptitle('Actual vs Predicted — XGBoost and Random Forest\n(Train and Test sets)',
             fontsize=13, fontweight='bold')

combos = [
    (axes[0,0], xgb_model, X_train, y_train, 'XGBoost — Train',    '#2d6a9f'),
    (axes[0,1], xgb_model, X_test,  y_test,  'XGBoost — Test',     '#2d6a9f'),
    (axes[1,0], rf_model,  X_train, y_train, 'Random Forest — Train', '#1e8449'),
    (axes[1,1], rf_model,  X_test,  y_test,  'Random Forest — Test',  '#1e8449'),
]

for ax, model, X, y, title, color in combos:
    pred_log = model.predict(X)
    actual   = np.expm1(y)
    predicted= np.expm1(pred_log)
    r2       = r2_score(actual, predicted)
    rmse     = np.sqrt(mean_squared_error(actual, predicted))

    ax.scatter(actual, predicted, alpha=0.2, s=8, color=color)
    lims = [min(actual.min(), predicted.min()) - 20,
            max(actual.max(), predicted.max()) + 20]
    ax.plot(lims, lims, 'k--', alpha=0.5, linewidth=1, label='Perfect prediction')
    ax.set_title(f'{title}\nR²={r2:.4f}  RMSE={rmse:.1f}', fontsize=10)
    ax.set_xlabel('Actual Sales Volume')
    ax.set_ylabel('Predicted Sales Volume')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)
    ax.text(0.05, 0.92, f'n={len(actual):,}', transform=ax.transAxes, fontsize=9, color='gray')

plt.tight_layout()
plt.savefig('/content/outputs/actual_vs_predicted.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: /content/outputs/actual_vs_predicted.png')

# ─────────────────────────────────────────────────────────────────────────────
# FINAL SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
print('\n' + '=' * 60)
print('ALL EVALUATION OUTPUTS SAVED')
print('=' * 60)
eval_outputs = [
    'train_vs_test_metrics.png',
    'correlation_matrix.png',
    'random_validation_20.csv',
    'random_validation_chart.png',
    'actual_vs_predicted.png',
]
import os
for f in eval_outputs:
    path = f'/content/outputs/{f}'
    size = os.path.getsize(path)/1024 if os.path.exists(path) else 0
    print(f'  ✅  {f:<40} {size:>7.1f} KB')

# ═══════════════════════════════════════════════════════════════════════════════
# TEAM 1 — CLASSIFICATION METRICS + CONFUSION MATRIX
#
# Since XGBoost and RF are REGRESSION models (they predict units sold, not a
# category), there is no native accuracy/precision/recall/F1.
#
# We convert predictions into 4 demand tiers and then compute classification
# metrics on those tiers — this is standard practice for regression evaluation
# in ERP and supply chain contexts.
#
# Demand Tiers:
#   Tier 0 — Low       : Sales Volume  518 –  900  (below average)
#   Tier 1 — Medium    : Sales Volume  901 – 1100  (around mean)
#   Tier 2 — High      : Sales Volume 1101 – 1400  (above average)
#   Tier 3 — Very High : Sales Volume 1401 – 1940  (top demand)
# ═══════════════════════════════════════════════════════════════════════════════

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report
)

# ── Tier bins and labels ──────────────────────────────────────────────────────
BINS   = [0, 900, 1100, 1400, 9999]
LABELS = ['Low\n(518–900)', 'Medium\n(901–1100)', 'High\n(1101–1400)', 'Very High\n(1401–1940)']
LABEL_SHORT = ['Low', 'Medium', 'High', 'Very High']

def to_tier(values):
    return pd.cut(values, bins=BINS, labels=[0, 1, 2, 3]).astype(int)

# ── Get actual and predicted values (raw scale) ───────────────────────────────
y_train_raw = np.expm1(y_train)
y_test_raw  = np.expm1(y_test)

xgb_train_pred = np.expm1(xgb_model.predict(X_train))
xgb_test_pred  = np.expm1(xgb_model.predict(X_test))
rf_train_pred  = np.expm1(rf_model.predict(X_train))
rf_test_pred   = np.expm1(rf_model.predict(X_test))

# ── Convert to tiers ──────────────────────────────────────────────────────────
y_train_tier     = to_tier(y_train_raw)
y_test_tier      = to_tier(y_test_raw)
xgb_train_tier   = to_tier(xgb_train_pred)
xgb_test_tier    = to_tier(xgb_test_pred)
rf_train_tier    = to_tier(rf_train_pred)
rf_test_tier     = to_tier(rf_test_pred)

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — METRICS TABLE
# ─────────────────────────────────────────────────────────────────────────────
print('=' * 70)
print('CLASSIFICATION METRICS (Demand Tier Prediction)')
print('Tiers: 0=Low  1=Medium  2=High  3=Very High')
print('=' * 70)

def compute_metrics(y_true, y_pred, label):
    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(y_true, y_pred, average='weighted', zero_division=0)
    f1   = f1_score(y_true, y_pred, average='weighted', zero_division=0)
    print(f'\n  {label}')
    print(f'  {"─" * 40}')
    print(f'  Accuracy  : {acc:.4f}  ({acc*100:.2f}%)')
    print(f'  Precision : {prec:.4f}  (weighted avg across all tiers)')
    print(f'  Recall    : {rec:.4f}  (weighted avg across all tiers)')
    print(f'  F1 Score  : {f1:.4f}  (weighted avg across all tiers)')
    return acc, prec, rec, f1

xgb_tr_acc, xgb_tr_prec, xgb_tr_rec, xgb_tr_f1 = compute_metrics(y_train_tier, xgb_train_tier, 'XGBoost — TRAIN')
xgb_ts_acc, xgb_ts_prec, xgb_ts_rec, xgb_ts_f1 = compute_metrics(y_test_tier,  xgb_test_tier,  'XGBoost — TEST')
rf_tr_acc,  rf_tr_prec,  rf_tr_rec,  rf_tr_f1  = compute_metrics(y_train_tier, rf_train_tier,  'Random Forest — TRAIN')
rf_ts_acc,  rf_ts_prec,  rf_ts_rec,  rf_ts_f1  = compute_metrics(y_test_tier,  rf_test_tier,   'Random Forest — TEST')

# Per-class breakdown
print('\n' + '=' * 70)
print('PER-CLASS BREAKDOWN — XGBoost (Test set)')
print('=' * 70)
print(classification_report(y_test_tier, xgb_test_tier,
                             target_names=LABEL_SHORT, zero_division=0))

print('=' * 70)
print('PER-CLASS BREAKDOWN — Random Forest (Test set)')
print('=' * 70)
print(classification_report(y_test_tier, rf_test_tier,
                             target_names=LABEL_SHORT, zero_division=0))

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — TRAIN vs TEST METRICS BAR CHART
# ─────────────────────────────────────────────────────────────────────────────
metric_names = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
x = np.arange(len(metric_names))
width = 0.18

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle(
    'Train vs Test Classification Metrics — Overfitting Check\n'
    'Demand Tier Classification  |  If Train >> Test → overfitting',
    fontsize=13, fontweight='bold'
)

for ax, model_label, train_vals, test_vals in [
    (axes[0], 'XGBoost',
     [xgb_tr_acc, xgb_tr_prec, xgb_tr_rec, xgb_tr_f1],
     [xgb_ts_acc, xgb_ts_prec, xgb_ts_rec, xgb_ts_f1]),
    (axes[1], 'Random Forest',
     [rf_tr_acc,  rf_tr_prec,  rf_tr_rec,  rf_tr_f1],
     [rf_ts_acc,  rf_ts_prec,  rf_ts_rec,  rf_ts_f1]),
]:
    gaps = [round(t - v, 4) for t, v in zip(train_vals, test_vals)]
    bars_tr = ax.bar(x - width/2, train_vals, width, label='Train', color='#2d6a9f')
    bars_ts = ax.bar(x + width/2, test_vals,  width, label='Test',  color='#1e8449')

    for bar, val in zip(bars_tr, train_vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{val:.4f}', ha='center', va='bottom', fontsize=8,
                fontweight='bold', color='#2d6a9f')
    for bar, val, gap in zip(bars_ts, test_vals, gaps):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{val:.4f}', ha='center', va='bottom', fontsize=8,
                fontweight='bold', color='#1e8449')
        gap_color = '#e74c3c' if abs(gap) > 0.05 else '#888888'
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.028,
                f'gap: {gap:+.4f}', ha='center', va='bottom',
                fontsize=7, color=gap_color)

    ax.set_title(f'{model_label}', fontsize=12, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(metric_names, fontsize=10)
    ax.set_ylabel('Score')
    ax.set_ylim(0, 1.15)
    ax.legend()
    ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('/content/outputs/classification_metrics_train_vs_test.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: classification_metrics_train_vs_test.png')

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — CONFUSION MATRICES (Train + Test for both models)
# ─────────────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(14, 12))
fig.suptitle('Confusion Matrices — Demand Tier Classification\nRows = Actual  |  Cols = Predicted',
             fontsize=13, fontweight='bold')

combos = [
    (axes[0,0], y_train_tier, xgb_train_tier, 'XGBoost — TRAIN'),
    (axes[0,1], y_test_tier,  xgb_test_tier,  'XGBoost — TEST'),
    (axes[1,0], y_train_tier, rf_train_tier,  'Random Forest — TRAIN'),
    (axes[1,1], y_test_tier,  rf_test_tier,   'Random Forest — TEST'),
]

for ax, y_true, y_pred, title in combos:
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1, 2, 3])

    # Normalised version (row-wise) for color, raw counts for annotation
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
    cm_norm = np.nan_to_num(cm_norm)

    sns.heatmap(
        cm_norm,
        annot=False,
        fmt='',
        cmap='Blues',
        vmin=0, vmax=1,
        linewidths=0.5,
        linecolor='white',
        ax=ax,
        cbar=True,
    )

    # Annotate each cell with count AND percentage
    for i in range(4):
        for j in range(4):
            count = cm[i, j]
            pct   = cm_norm[i, j] * 100
            color = 'white' if cm_norm[i, j] > 0.5 else 'black'
            ax.text(j + 0.5, i + 0.42,
                    f'{count}',
                    ha='center', va='center',
                    fontsize=12, fontweight='bold', color=color)
            ax.text(j + 0.5, i + 0.65,
                    f'({pct:.1f}%)',
                    ha='center', va='center',
                    fontsize=9, color=color)

    acc  = accuracy_score(y_true, y_pred)
    ax.set_title(f'{title}\nAccuracy: {acc:.4f}  ({acc*100:.2f}%)', fontsize=11, fontweight='bold')
    ax.set_xticklabels(LABEL_SHORT, fontsize=9)
    ax.set_yticklabels(LABEL_SHORT, fontsize=9, rotation=0)
    ax.set_xlabel('Predicted Tier', fontsize=10)
    ax.set_ylabel('Actual Tier',    fontsize=10)

plt.tight_layout()
plt.savefig('/content/outputs/confusion_matrices.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: confusion_matrices.png')

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — SUMMARY TABLE (clean printout)
# ─────────────────────────────────────────────────────────────────────────────
print('\n' + '=' * 70)
print('FINAL SUMMARY — ALL METRICS')
print('=' * 70)
summary = pd.DataFrame({
    'Model'    : ['XGBoost', 'XGBoost', 'Random Forest', 'Random Forest'],
    'Split'    : ['Train', 'Test', 'Train', 'Test'],
    'Accuracy' : [f'{xgb_tr_acc:.4f}', f'{xgb_ts_acc:.4f}', f'{rf_tr_acc:.4f}', f'{rf_ts_acc:.4f}'],
    'Precision': [f'{xgb_tr_prec:.4f}', f'{xgb_ts_prec:.4f}', f'{rf_tr_prec:.4f}', f'{rf_ts_prec:.4f}'],
    'Recall'   : [f'{xgb_tr_rec:.4f}', f'{xgb_ts_rec:.4f}', f'{rf_tr_rec:.4f}', f'{rf_ts_rec:.4f}'],
    'F1 Score' : [f'{xgb_tr_f1:.4f}', f'{xgb_ts_f1:.4f}', f'{rf_tr_f1:.4f}', f'{rf_ts_f1:.4f}'],
})
print(summary.to_string(index=False))

print('\nNote: Metrics computed by bucketing predicted Sales Volume into 4 demand tiers:')
print('  Tier 0 — Low       :  518 –  900 units')
print('  Tier 1 — Medium    :  901 – 1100 units')
print('  Tier 2 — High      : 1101 – 1400 units')
print('  Tier 3 — Very High : 1401 – 1940 units')